name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage lcov

      - name: Run tests
        run: |
          coverage run -m unittest discover
          coverage xml -o coverage.xml
          lcov --capture --directory . --output-file lcov.info

      - name: Upload coverage to SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=La-maker-lab24_Lab2
            -Dsonar.organization=la-maker-lab24
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.python.coverage.reportPaths=lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      - name: Run SonarCloud analysis
        run: sonar-scanner
