name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage lcov
          
      - name: Install lcov
        run: sudo apt-get install lcov

      # Установка Java 17
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version  # Проверка установленной версии Java

      - name: Run tests
        run: |
          coverage run -m unittest discover
          coverage xml -o coverage.xml
          lcov --capture --directory . --output-file lcov.info

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master # Используем последнюю стабильную версию
        with:
          args: >
            -Dsonar.projectKey=La-maker-lab24_Lab2
            -Dsonar.organization=la-maker-lab24
            -Dsonar.sources=./files/
            -Dsonar.tests=.test_game.py
            -Dsonar.python.coverage.reportPaths=lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

