name: Python Tests

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage coveralls

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report
        coverage xml

    - name: Upload coverage to Coveralls
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=La-maker-lab24_Lab2
            -Dsonar.organization=la-maker-lab24
            -Dsonar.sources=https://github.com/La-maker-lab24/Lab2
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Укажите путь к отчету о покрытии
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
